---

##########
# Headers for config files
##########
ansible:

  view_encrypted_file_cmd: "ansible-vault --vault-password-file {{ playbook_dir }}/../{{ lookup('env', 'ANSIBLE_VAULT_PASSWORD_FILE') }} view "

  headers:
    bash: "### THIS FILE IS MANAGED BY ANSIBLE ###"
    python: "### THIS FILE IS MANAGED BY ANSIBLE ###"

#######
# Pinned package versions
#######
pinning_config_map:
  nodejs: "5.11.1*"

#######
# Travis
#######
not_travis: "{{ not (is_travis | default(False)) }}"

...
