---

#####
# Nginx enabled sites
#####
nginx_sites_enabled:
  customer:
    template: "templates/sites-enabled/app.himate.org.conf.j2"
    domain: "{{ app_customer_domain }}"
    ssl_cert: "{{ nginx_dev_ssl_cert }}"
    ssl_key: "{{ nginx_dev_ssl_key }}"
  merchant:
    template: "templates/sites-enabled/merchant.himate.org.conf.j2"
    domain: "{{ app_merchant_domain }}"
    ssl_cert: "{{ nginx_dev_ssl_cert }}"
    ssl_key: "{{ nginx_dev_ssl_key }}"
  admin:
    template: "templates/sites-enabled/admin.himate.org.conf.j2"
    domain: "{{ app_admin_domain }}"
    ssl_cert: "{{ nginx_dev_ssl_cert }}"
    ssl_key: "{{ nginx_dev_ssl_key }}"

...
