---

- name: Include customer specific variables
  include_vars: "{{ ansible_distribution }}{{ ansible_distribution_version }}_customer.yml"
  when: "{{ 'customer' in app_types }}"

- name: Include customer app deploy
  include: "{{ ansible_distribution }}{{ ansible_distribution_version }}_customer.yml"
  when: "{{ 'customer' in app_types }}"

- name: Include merchant specific variables
  include_vars: "{{ ansible_distribution }}{{ ansible_distribution_version }}_merchant.yml"
  when: "{{ 'merchant' in app_types }}"

- name: Include merchant app deploy
  include: "{{ ansible_distribution }}{{ ansible_distribution_version }}_merchant.yml"
  when: "{{ 'merchant' in app_types }}"

- name: Include admin specific variables
  include_vars: "{{ ansible_distribution }}{{ ansible_distribution_version }}_admin.yml"
  when: "{{ 'admin' in app_types }}"

- name: Include admin app deploy
  include: "{{ ansible_distribution }}{{ ansible_distribution_version }}_admin.yml"
  when: "{{ 'admin' in app_types }}"
