---

sudo: required
dist: trusty
language: python
python: '2.7'

addons:
  hosts:
    - travis-app
    - travis-master

install:
  - pip install ansible==${ANSIBLE_VERSION}
  - openssl aes-256-cbc -k "$vault_file_pass" -in vault_pass.enc -out vault_pass -d
  - ${TRAVIS_BUILD_DIR}/.travis/sensitive_data.sh decrypt

script:
  - >
    ANSIBLE_VAULT_PASSWORD_FILE=vault_pass
    ansible-playbook ${PLAYBOOK}
    -i inventories/travis
    --syntax-check
    --extra-vars "${EXTRAVARS}"

  - >
    ANSIBLE_VAULT_PASSWORD_FILE=vault_pass
    ansible-playbook ${PLAYBOOK}
    -i inventories/travis
    --connection=local
    --become
    --extra-vars "${EXTRAVARS}"

  - >
    ANSIBLE_VAULT_PASSWORD_FILE=vault_pass
    ansible-playbook ${PLAYBOOK}
    -i inventories/travis
    --connection=local
    --become
    --extra-vars "${EXTRAVARS}"
    | tee /tmp/output.txt; grep -q 'changed=0.*failed=0' /tmp/output.txt && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)

after_script:
  - ${TRAVIS_BUILD_DIR}/.travis/sensitive_data.sh clean
  - shred vault_pass

env:
  global:
    - secure: "DtNbh7+iKwx0HFc+RZoxhmIspTpkcKTJnH7gS1fiXut+UQ0fTeR2JfRvNMxUMrCy9o0R07VyEo3hwjmtClZrUsLnicbJKRcesNTC1KKrZWsHJWxX/XODrjIMd2ag7jlhLrvKfhDT4OIP20Q6gjFk8vM7CVGwzEmYdth+MrgwiFVKN+YcWqDPv4wYTEDf3S55FYC7uVMfE1tpq4mHUNfv+BUcYmuzP9LOFplJ7DwLUf129oQOdJJXMBBubPwuWK0oaB3e6fqhbxuIq1tuJBxX8SppiFx8Gd//wZStl1D5M+0MHnxwCb4DOSDtOCPxeV/Hk5xbNTPCYOLll978egDUBnUQykjwvQb3gvOJrjdTzAfQ5XT5TKT7KW/gg6dYIhtOiLdwAuuxbsWATJJ808UgZGZ/u4OxqdZ/E5EJdquLDw99pb5SYM/eAv2R4/Kms/rEPxTXyZLfr0Y5jjjZa8tpj6Kf/L7zk++GJ9BHn5qfsQDfKCMsPWe0UFT27j7JRMQKFv03GA529FhTyX6lNlKhC/KgfxPYlZZRheOtbgsadEHsajw3bej6tFAPHHDCtMS9SYSoOcdpAcZvSNmNKkotAbALMW5fusJKiVmOwIBDYp72NAaFbpbS05slf+BCstRMmjHZBCQXvyiZQXD0vgdY9uRR2ZNQJSLiAW5hbnmjpfw="
    - ANSIBLE_VERSION=2.1

  matrix:
    - PLAYBOOK: "playbooks/app.yml"
      EXTRAVARS: "@.travis/app_extra_vars.json"
    - PLAYBOOK: "playbooks/master.yml"
      EXTRAVARS: "@.travis/master_extra_vars.json"

notifications:
  slack:
    rooms:
      - secure: "HkBmDmTrUKUMpReVRyNVxF5Lc+fZWkhptYn1dFGcvgFo++toXmD0mHQO5waDTticU+8kfl2umojztzQl+mtqEq+u9vUqff2qkGvUXBLuvCOh18Tj7pgDx/JN1rxjvqMQrgGx0/rJETGiyITLJAO6AHdnAsX1axex4sU503qr8Pldu7f530HpMq8peBrTnnugzFbFnHgP3w7wopFIoxWY8oi7AqO62r33aZLmFz8RQZG3PXN3K81MOHWKyYo6YWiD4IuNaugAkHkTULYZRyHeJAfY+31YzOxDCGvTTi1Mo+eV4aINBVOvYGs/n4xmkVEO+WQhHaIrdiU15YCHrB307QKrcYa/ncPAaRozZWlW+/qKG2fute51i4MtrUPQWUv/htAkASlxllMdu9rIrdAqL3HXCpTwREab8VyRxEs605aB/0gZMQ8sWKUAR+MvngiMgShb4wctuvfUo0oo2JjRkQoj/6ekptNPyCMiFQYDdh/NxHbVy6Q1wltdnpopFaMROjalIHDHw+ndamkk+D832lB7yQRji4+PnfFo+OesAqxnE+2tYdhqB9MC0AgvzTvGYqRXwjsMNy5h08CnDW3jKYg9lTLQK81irlQm2jczBHYNlxMrxNwA/48xNjWUGjpunKdIAJ3a0o4MArmEGbhCjrWfcA1lHv9eUIGKuNNnUEk="

...
