---

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}{{ ansible_distribution_version }}.yml"

- name: Include distribution specific installation
  include: "{{ ansible_distribution }}{{ ansible_distribution_version }}.yml"

- name: Create logrotate configurations
  template:
    src={{ item.value.template }}
    dest={{ logrotate_conf_dir }}/{{ item.value.conf_name }}
    owner={{ logrotate_user }}
    group={{ logrotate_group }}
    mode={{ logrotate_conf_mode }}
  with_dict: "{{ logrotate_config_map | default({}) }}"

...
