---

- name: ssh distribution specific vars
  include_vars: "{{ ansible_distribution }}{{ ansible_distribution_version }}.yml"

- name: ssh distribution specific install
  include: "{{ ansible_distribution }}{{ ansible_distribution_version }}.yml"
  when: "{{ sshd_do_configure | default(True) }}"

- name: Add sshd_config
  template:
    src={{ sshd_config_template }}
    dest={{ sshd_config_dest }}
    owner={{ sshd_config_owner }}
    group={{ sshd_config_group }}
    mode={{ sshd_config_mode }}
  notify: "{{ sshd_service_restart_id }}"
  when: "{{ sshd_do_configure | default(True) }}"
  vars:
    all_groups: "{{ user_group_list }}"

...
