---

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}{{ ansible_distribution_version }}.yml"

- name: Include distribution specific installation
  include: "{{ ansible_distribution }}{{ ansible_distribution_version }}.yml"

- name: Deploy ntpd.conf
  template:
    src={{ openntpd_conf_template }}
    dest={{ openntpd_conf_file }}
    mode={{ openntpd_conf_file_mode }}
    owner={{ openntpd_conf_file_owner }}
    group={{ openntpd_conf_file_group }}
  notify: "{{ openntpd_restart_id }}"

...
