---

- name: Create admin app dir
  file:
    path={{ app_admin_dir }}
    owner={{ app_admin_dir_owner }}
    group={{ app_admin_dir_group }}
    mode={{ app_admin_dir_mode }}
    state=directory

- name: Deploy admin start script
  template:
    src=templates/start.admin.sh.j2
    dest={{ app_admin_dir }}/start.sh
    owner={{ app_admin_dir_owner }}
    group={{ app_admin_dir_group }}
    mode=740

- name: Deploy admin stop script
  template:
    src=templates/stop.admin.sh.j2
    dest={{ app_admin_dir }}/stop.sh
    owner={{ app_admin_dir_owner }}
    group={{ app_admin_dir_group }}
    mode=740

...
