---

- name: Create customer app dir
  file:
    path={{ app_customer_dir }}
    owner={{ app_customer_dir_owner }}
    group={{ app_customer_dir_group }}
    mode={{ app_customer_dir_mode }}
    state=directory

- name: Deploy customer start script
  template:
    src=templates/start.customer.sh.j2
    dest={{ app_customer_dir }}/start.sh
    owner={{ app_customer_dir_owner }}
    group={{ app_customer_dir_group }}
    mode=740

- name: Deploy customer stop script
  template:
    src=templates/stop.customer.sh.j2
    dest={{ app_customer_dir }}/stop.sh
    owner={{ app_customer_dir_owner }}
    group={{ app_customer_dir_group }}
    mode=740

...
