- name: Add groups
  group:
    name={{ item.groupname }}
    gid={{ item.gid }}
    state={{ item.state }}
  with_items: "{{ user_group_list }}"


- name: Add admin groups to sudoers
  template: 
    src=templates/sudoers.group.j2
    dest=/etc/sudoers.d/{{ item.groupname }}_group
    mode=0440
    owner=root
    group=root
  when: "{{ item.sudoers | default(False) }}"
  with_items: "{{ user_group_list }}"
