- name: Inlcude group creation
  include: groups.yml


- name: Include user creation
  include: users.yml


# include sudoers last to avoid permission issues!
- name: Include sudoers configuration
  include: sudoers_file.yml
