---

- name: Add users
  user: 
    name={{ item.username }} 
    uid={{ item.uid }} 
    groups={{ item.groups | default('') }} 
    shell={{ item.shell }} 
    state={{ item.state }}
    home={{ item.home | default("/home/" + item.username) }}
    comment={{ item.name }} ({{ item.email }})
  when: "{{ item.state == 'present' }}"
  with_items: "{{ user_list }}"


- name: Remove users
  user: 
    name={{ item.username }} 
    remove=yes
    force=yes
    state=absent
  when: "{{ item.state == 'absent' }}"
  with_items: "{{ user_list }}"


- name: Add authorized keys for users
  authorized_key:
    user={{ item.username }}
    key={{ lookup('pipe', ansible.view_encrypted_file_cmd + item.authorized_keys) }}
    state={{ item.username_state | default('present') }}
  when: "{{ item.authorized_keys is defined and item.state == 'present' }}"
  with_items: "{{ user_list }}"


- name: Ensure .ssh dir exists for user
  file: 
    path={{ item.home | default("/home/" + item.username) }}/.ssh
    owner={{ item.username }}
    group={{ item.username }}
    state=directory 
    mode=700
  when: "{{ item.state == 'present' }}"
  with_items: "{{ user_list }}"


- name: Add private usernames for user
  copy: 
    src={{ item.private_username }}
    dest=/home/{{ item.username }}/.ssh/id_rsa
    owner={{ item.username }}
    group={{ item.username }}
    mode=600
  when: "{{ item.private_username is defined and item.state == 'present' }}"
  with_items: "{{ user_list }}"


- name: Add public usernames for user
  copy: 
    src={{ item.public_username }}
    dest=/home/{{ item.username }}/.ssh/id_rsa.pub
    owner={{ item.username }}
    group={{ item.username }}
    mode=600
  when: "{{ item.public_username is defined and item.state == 'present' }}"
  with_items: "{{ user_list }}"


- name: Add vimrc for users
  copy: 
    src={{ item.vimrc }}
    dest=/home/{{ item.username }}/.vimrc
    owner={{ item.username }}
    group={{ item.username }}
    mode=644
  when: "{{ item.vimrc is defined and item.state == 'present' }}"
  with_items: "{{ user_list }}"

...
