---

- name: java distribution specific vars
  include_vars: "{{ ansible_distribution }}{{ ansible_distribution_version }}.yml"

- name: java distribution specific install
  include: "{{ ansible_distribution }}{{ ansible_distribution_version }}.yml"
  when: "{{ sshd_do_configure | default(True) }}"

...
