---

- name: jenkins distribution specific vars
  include_vars: "{{ ansible_distribution }}{{ ansible_distribution_version }}.yml"

- name: jenkins distribution specific install
  include: "{{ ansible_distribution }}{{ ansible_distribution_version }}.yml"

- name: Deploy jenkins config
  template:
    src={{ jenkins_config_template }}
    dest={{ jenkins_config }}
    mode=0644
    owner=root
    group=root
  notify: "{{ jenkins_service_restart_id }}"

- name: Create jenkins log dir
  file:
    path={{ jenkins_log_dir }}
    owner={{ jenkins_user }}
    group={{ jenkins_group }}
    state=directory 
    mode=740

...
