---

- name: Install necessary pip packages for get_url
  pip:
    name={{ item }}
  with_items: "{{ meteor_pip_requirements }}"

- name: Get meteor install script
  get_url:
    url={{ meteor_install_script_url }}
    dest=/tmp/meteor-install.sh
    mode=755

- name: Install meteor version {{ meteor_version }}
  shell: "/tmp/meteor-install.sh && su {{ himate_dirs.app.owner }} -c 'meteor --release {{ meteor_version }} --version'"
  args:
    creates: /usr/local/bin/meteor
